package roles

import (
	"context"
	"fmt"
	"os/exec"
	"strconv"
	"strings"
	"time"

	tea "github.com/charmbracelet/bubbletea"
	"github.com/objectisnotdefined/consensus-agent/ca/internal/agent"
	"github.com/objectisnotdefined/consensus-agent/ca/internal/blackboard"
	"github.com/objectisnotdefined/consensus-agent/ca/internal/consensus"
	"github.com/objectisnotdefined/consensus-agent/ca/pkg/llm"
)

const validatorSystemPrompt = `You are a Senior Security & Quality Auditor.
Your task is to review the code generated by an AI Executor and compare it against the provided Architectural Plan.

CRITICAL INSTRUCTIONS:
1. Check for logical correctness and adherence to the plan.
2. Identify potential bugs, security vulnerabilities, or anti-patterns.
3. Verify that the code is production-ready and follows best practices.
4. Rate the overall implementation on a scale of 0.0 to 1.0.

Your output MUST end with the following format exactly:
REPORT: [Summary of findings]
SCORE: [0.0 - 1.0]`

type Validator struct {
	bb       blackboard.Blackboard
	selector *llm.Selector
	status   agent.Status
	logs     []agent.LogEntry
	msgChan  chan tea.Msg
}

func NewValidator(bb blackboard.Blackboard, selector *llm.Selector) *Validator {
	return &Validator{
		bb:       bb,
		selector: selector,
		status:   agent.StatusIdle,
		msgChan:  make(chan tea.Msg, 100),
	}
}

func (v *Validator) Role() agent.Role       { return agent.RoleValidator }
func (v *Validator) Status() agent.Status   { return v.status }
func (v *Validator) Logs() []agent.LogEntry { return v.logs }

func (v *Validator) Reset() {
	v.status = agent.StatusIdle
	v.logs = nil
	for len(v.msgChan) > 0 {
		<-v.msgChan
	}
}

func (v *Validator) Next() tea.Cmd {
	return func() tea.Msg {
		return <-v.msgChan
	}
}

func (v *Validator) Start(ctx context.Context, task string, workspace string) tea.Cmd {
	v.status = agent.StatusRunning

	go func() {
		v.log("INFO", "🛡 Starting multi-track validation...")

		// 1. Get Context from Blackboard
		sbPathVal, _ := v.bb.Get(consensus.KeySandboxPath)
		sbPath, _ := sbPathVal.(string)
		
		planVal, _ := v.bb.Get(consensus.KeyArchitectPlan)
		plan, _ := planVal.(string)
		
		codeVal, _ := v.bb.Get(consensus.KeyExecutorCode)
		code, _ := codeVal.(string)

		// 2. Track 1: SAST (golangci-lint & gosec)
		v.log("INFO", "Track 1: Running SAST scans (static analysis)...")
		sastScore := v.runSAST(sbPath)
		v.bb.Set(consensus.KeySASTPassRate, sastScore)

		// 3. Track 2: Semantic Review (LLM-based)
		v.log("INFO", "Track 2: Initiating LLM semantic code review...")
		
		// Select Model
		client, err := v.selector.SelectByRole("Validator")
		if err != nil {
			v.log("ERROR", fmt.Sprintf("No model found for Validator: %v", err))
			v.emitStatus(agent.StatusFailed)
			return
		}
		v.log("INFO", fmt.Sprintf("Using model: %s (%s)", client.Name(), client.Provider()))

		// Prepare context for review
		reviewContext := fmt.Sprintf("User Task: %s\n\nArchitectural Plan:\n%v\n\nGenerated Code:\n%v", task, plan, code)

		resp, err := client.Chat(ctx, llm.CompletionRequest{
			Messages: []llm.Message{
				{Role: llm.RoleSystem, Content: validatorSystemPrompt},
				{Role: llm.RoleUser, Content: reviewContext},
			},
			Temperature: 0.1,
		})

		if err != nil {
			v.log("ERROR", fmt.Sprintf("Semantic review failed: %v", err))
			v.emitStatus(agent.StatusFailed)
			return
		}

		// 4. Parse Score and Report
		report, score := parseReviewResponse(resp.Content)
		v.log("INFO", fmt.Sprintf("Review complete. Semantic Score: %.2f", score))
		
		v.bb.Set(consensus.KeySemanticAgreement, score)
		v.bb.Set(consensus.KeyTestPassRate, score) // For Phase 1, we use semantic score as a proxy for test pass rate if tests aren't run
		v.bb.Set(consensus.KeyValidatorReport, report)

		v.log("INFO", "✅ Validation suite complete.")
		v.emitStatus(agent.StatusDone)
	}()

	return v.Next()
}

func parseReviewResponse(content string) (string, float64) {
	lines := strings.Split(content, "\n")
	var report string
	score := 0.0

	for _, line := range lines {
		if strings.HasPrefix(line, "REPORT: ") {
			report = strings.TrimPrefix(line, "REPORT: ")
		} else if strings.HasPrefix(line, "SCORE: ") {
			valStr := strings.TrimSpace(strings.TrimPrefix(line, "SCORE: "))
			if f, err := strconv.ParseFloat(valStr, 64); err == nil {
				score = f
			}
		}
	}

	if report == "" {
		report = "Review complete."
	}
	return report, score
}

func (v *Validator) runSAST(path string) float64 {
	score := 1.0
	
	// Track issues
	issues := 0

	// 1. golangci-lint
	v.log("INFO", "  → Executing golangci-lint...")
	if _, err := exec.LookPath("golangci-lint"); err != nil {
		v.log("WARN", "    [!] golangci-lint not found. Skipping...")
	} else {
		cmd := exec.Command("golangci-lint", "run", "./...")
		cmd.Dir = path
		out, err := cmd.Output()
		if err != nil {
			// golangci-lint returns 1 if issues found
			issues += 1 // Simplified: just mark as having issues
			v.log("WARN", "    [✘] golangci-lint found issues.")
			fmt.Println(string(out))
		} else {
			v.log("INFO", "    [✔] golangci-lint passed.")
		}
	}

	// 2. gosec
	v.log("INFO", "  → Executing gosec security scan...")
	if _, err := exec.LookPath("gosec"); err != nil {
		v.log("WARN", "    [!] gosec not found. Skipping...")
	} else {
		cmd := exec.Command("gosec", "-quiet", "./...")
		cmd.Dir = path
		if err := cmd.Run(); err != nil {
			issues += 1
			v.log("WARN", "    [✘] gosec found potential security vulnerabilities.")
		} else {
			v.log("INFO", "    [✔] gosec security check passed.")
		}
	}

	if issues > 0 {
		score = 0.5 // Simplified penalty
	}

	return score
}

func (v *Validator) log(level, msg string) {
	entry := agent.LogEntry{
		Timestamp: time.Now(),
		Level:     level,
		Message:   msg,
	}
	v.logs = append(v.logs, entry)
	v.msgChan <- agent.LogMsg{Role: v.Role(), Entry: entry}
}

func (v *Validator) emitStatus(s agent.Status) {
	v.status = s
	v.msgChan <- agent.StatusMsg{Role: v.Role(), Status: s}
}
